### ISSUE TITLE
请问一下PC怎么用啊，我下载了PC

### ISSUE THREAD

**Issue by claire360** [844704781/ximalaya_downloader#1]
Error: 暂不支持: true 这种登录方式
    at DownloaderFactory._login (file:///D:/info/person/%E7%A0%94%E4%BA%8C%E4%B8%8B/ximalaya_downloader-main/handler/downloader.js:49:19)
    at DownloaderFactory.getDownloader (file:///D:/info/person/%E7%A0%94%E4%BA%8C%E4%B8%8B/ximalaya_downloader-main/handler/downloader.js:96:24)
    at main (file:///D:/info/person/%E7%A0%94%E4%BA%8C%E4%B8%8B/ximalaya_downloader-main/xmd.js:133:37)
    at file:///D:/info/person/%E7%A0%94%E4%BA%8C%E4%B8%8B/ximalaya_downloader-main/xmd.js:221:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.15.0

**Comment by 844704781** [comment]
你好,这几天事情有些多，过些天我会发布一个带界面的版本
